优化代码，解决构建问题：Run python3 res/inline-sciter.py error: failed to parse manifest at `D:\a\rustdesk\rustdesk\Cargo.toml`
Caused by:
  feature `unix-file-copy-paste` includes `dep:x11-clipboard`, but `x11-clipboard` is not listed as a dependency
Error: Process completed with exit code 101.
注意为撒谎构建的时候windwos的x64的构建版本没有了
auto_coder_000000000011_chat_action.yml